### ISSUE TITLE
API: Define endpoints and connect logic with database models

### ISSUE THREAD

**Issue by vainamov** [festivaledu/Pakketti#4]
The individual endpoints are going to be determined during the process.

**Comment by SniperGER** [comment]
Account controller added with 7cc1b6e

**Comment by SniperGER** [comment]
Ratings & Reviews added with 435523b

**Comment by SniperGER** [comment]
Statistics added with bf5859c

**Comment by SniperGER** [comment]
Requests added with f6fd109

**Comment by SniperGER** [comment]
Moderation log controller has been added with 66836bd. Moving on to documenting every model and endpoint now, as this marks the end of the _planned_ endpoints.

_Note to self: this isn't true. We're still missing the Devices controller to link iOS (and probably other) devices to the database. But I'm documenting this stuff anyways now._

**Comment by SniperGER** [comment]
Device controller added with 9119efdc80c84cff1f2830b7c386f7f6ad104376, which allows manually adding _any_ device to an account. Linking iOS devices using a Configuration Profile will follow soon.

**Comment by SniperGER** [comment]
File handling (package files, screenshots) implemented with b623ef6
